"""
Transparency labels: the exact text shown to a reader on the platform.
Three variants, written out here verbatim (also quoted in README.md).
"""

LABEL_TEXT = {
    "likely_ai": (
        "Likely AI-Generated \u2014 Our system detected strong signals that this "
        "content was generated by an AI model. If you believe this is incorrect, "
        "you can appeal this classification."
    ),
    "likely_human": (
        "Likely Human-Written \u2014 Our system found this content consistent with "
        "human authorship."
    ),
    "uncertain": (
        "Uncertain \u2014 Our system could not confidently determine whether this "
        "content is AI-generated or human-written. Treat this result as "
        "inconclusive. You can appeal this classification for human review."
    ),
}


def generate_label(attribution, confidence):
    """Returns the label text plus the numeric confidence for transparency."""
    base_text = LABEL_TEXT[attribution]
    return f"{base_text} (confidence score: {confidence})"
